terraform 생성 및 삭제에 따라 endpoint url을 db에 등록 및 삭제 하도록 변경
kookmin-sw/capstone-2024-12 pull request #37
Opened 2024-04-30 08:20 UTC by jhM00n

endpoint url을 db에 등록하도록 변경함.
추론 db는 아래와 같음
```
{    
    "user": "",
    "name": "",
    "model": "",
    "type": "",
    "endpoint": ""
}
```
- user: user_uid
- name: endpoint name
- model: model_uid
- tpye: spot or serverless
- endpoint: endpoint url
---
- lambda handler 실행 시 없는 parameter가 존재할 경우 에러가 발생하므로 전체 파라미터를 받은 후 따로 get 하도록 변경
    - terraform apply 시 inference_uid는 필요 없으므로
- inference uid가 존재하면 destroy를 진행하도록 변경
    - destroy를 진행하면서 db에 등록한 endpoint url을 삭제
    - 삭제 시 inference uid는 콘솔에서 제공함
- inference uid가 없다면 create를 진행
    - endpoint를 생성 후 endpoint url을 db에 등록
- terraform.state를 s3에 저장하는 경로는 다음과 같음
    - "{user_uid}/{model_uid}/{type}/{endpoint_name}/terraform.state"

2024-04-30 08:27 UTC, mh3ong commented
trello에 어떻게 돌아가서 s3랑 db에 어떻게 기록되는지 update 바람.

2024-05-02 08:12 UTC, mh3ong commented
ecr push sample 어디 ?

2024-05-02 08:22 UTC, jhM00n commented
추가함

2024-05-02 08:23 UTC, mh3ong requested changes

2024-05-02 08:23 UTC, mh3ong commented on automation/serverless_inference_deploy/push_aws_ecr.sh.sample
> +docker push [ecr uri]/serverless-inference-deploy:latest
[ecr uri] 와 같은 형식이 아니라 변수로 처리

2024-05-02 08:25 UTC, jhM00n commented on automation/serverless_inference_deploy/lambda.py
> +            response = requests.delete(delete_inference_url)
db에서 삭제하는 코드

2024-05-02 08:25 UTC, jhM00n commented on automation/serverless_inference_deploy/push_aws_ecr.sh.sample
> +docker push [ecr uri]/serverless-inference-deploy:latest
그럼 변수 입력받는것도 만들어?

2024-05-02 08:25 UTC, mh3ong commented on automation/serverless_inference_deploy/lambda.py
> +            response = requests.delete(delete_inference_url)
실제 url 입력 이게 맞나?
env로 처리를하던지...

2024-05-02 08:28 UTC, mh3ong commented on automation/serverless_inference_deploy/push_aws_ecr.sh.sample
> +docker push [ecr uri]/serverless-inference-deploy:latest
no 설정하는것으로

2024-05-02 10:43 UTC, jhM00n commented
lambda가 endpoint url을 db에 등록할 때, db 주소를 env를 사용하도록 수정함
env는 INFERENCE_URL 하나만 사용함

2024-05-02 11:06 UTC, jhM00n commented
env name을 db_api_url로 변경
lambda.py의 inference url 부분에 https:// 추가

2024-05-02 11:07 UTC, mh3ong commented on automation/serverless_inference_deploy/lambda.py
>          bucket = "sskai-terraform-state"
bucket name도 env 처리가 필요할듯.

2024-05-02 11:08 UTC, mh3ong commented on automation/serverless_inference_deploy/lambda.py
>          bucket = "sskai-terraform-state"
STATE_BUCKET_NAME

2024-05-02 11:29 UTC, jhM00n commented
endpoint url 수정 및 bucket env 추가

2024-05-02 11:39 UTC, mh3ong approved these changes

2024-05-02 11:41 UTC, merged