모델 프로파일 API 버전 1 완성
kookmin-sw/capstone-2024-12 pull request #62
Opened 2024-05-11 12:14 UTC by seungwoo1124

작업 내용
- EKS Kubernetes job 으로 작동하는 프로파일 로직 및 파드 이미지 작성
- 해당 Job 배포하기 위한 Lambda 자동화 코드 작성
- subprocess returncode 확인하도록 변경

2024-05-11 12:25 UTC, mh3ong requested changes

2024-05-11 12:25 UTC, mh3ong commented on automation/karpenter_node_pool_deploy/deploy_nodepool.sh.sample
> +curl $LAMBDA_URL
이것은 무엇을 위해 존재하는 파일인지?

2024-05-11 12:25 UTC, mh3ong commented on automation/karpenter_node_pool_deploy/nodepool_generator.py
>      ssm = boto3.client('ssm', region_name='ap-northeast-2')
region 변수 처리 필요

2024-05-12 04:15 UTC, seungwoo1124 commented on automation/karpenter_node_pool_deploy/deploy_nodepool.sh.sample
> +curl $LAMBDA_URL
노드풀 배포를 테스트 하는 코드입니다. 람다 생성 후 console 에서 test 진행해도 되지만 curl 을 이용하여 테스트 하여 반환값을 받아볼 수 있습니다.

2024-05-12 04:26 UTC, seungwoo1124 commented on automation/karpenter_node_pool_deploy/nodepool_generator.py
>      ssm = boto3.client('ssm', region_name='ap-northeast-2')
처리완료

2024-05-12 05:05 UTC, merged