add the dev foundation model codes
kookmin-sw/capstone-2024-12 pull request #64
Opened 2024-05-11 16:04 UTC by Kim-Yul

파운데이션 모델 stable diffusion을 위한 코드 초안입니다.
아직 로직적으로 이야기할 것이 좀 있어서 얘기하고 완성할 예정입니다.

2024-05-12 05:15 UTC, mh3ong requested changes

2024-05-12 05:15 UTC, mh3ong commented on foundation_model/stable_diffusion/train.py
> +            save_lora_weights(unet.module, text_encoder.module, config["output_dir"])
text_encoder.module, unet.module을 각각 text_encoder, unet으로 수정 필요.

2024-05-12 10:16 UTC, mh3ong commented on foundation_model/stable_diffusion/train_main.py
> +            storage_path=f"s3://sskai-checkpoint-test/{user_id}", # "s3://{bucket_name}/{user_name}
storage path를 user_id로 하는게 올바른것인지?

2024-05-12 10:16 UTC, mh3ong commented on foundation_model/stable_diffusion/flags.py
> +        default="b95be7d6f134c3a9e62ee616f310733567f069ce",
이 값은 무슨의미가 있는것인지?

2024-05-12 10:16 UTC, mh3ong commented on foundation_model/stable_diffusion/inf_main.py
> +    model_path = "/tmp/trained_model/stable_diffusion/models--CompVis--stable-diffusion-v1-4/snapshots/b95be7d6f134c3a9e62ee616f310733567f069ce"
위에서는 default에 지정하고 여기서 변수에 활용안하는 이유가 있는지?

2024-05-12 10:20 UTC, jhM00n commented on foundation_model/stable_diffusion/train_main.py
> +            storage_path=f"s3://sskai-checkpoint-test/{user_id}", # "s3://{bucket_name}/{user_name}
잠깐 이부분은 내 작업내용이 아닌데

2024-05-15 10:59 UTC, Kim-Yul commented on foundation_model/stable_diffusion/flags.py
> +        default="b95be7d6f134c3a9e62ee616f310733567f069ce",
git 의 커밋코드와 같이 허깅페이스 커밋 코드라고 생각해주시면 될 것 같습니다.
모델 훈련할 때 사용한 값으로 지정해두었습니다.

2024-05-15 12:56 UTC, Kim-Yul commented
## stable diffusion file
- dataset .py : 사용자의 이미지 파일을 torch에서 사용할 수 있게 변환하고, 로드하는 작업을 진행
- flags.pt : 커맨드 args를 받아 파일에 적용함. 없는 값은 defalut 값을 설정함.
- generate.py : 이미지를 생성 (사용자가 훈련시킬 이미지 class의 정규화 이미지를 생성하거나 모델의 추론을 통해 이미지를 생성할 때 필요함.)
- generate_utils.py : 이미지 생성할 때 사용하는 함수가 따로 분리되어 있음. lora_weights와 pipeline 함수를 정의함.
- train.py : 모델 훈련을 진행함.
- train_executable_file.py : main 실행 파일에 넣어야 하는 args 값을 변수로 선언하여 실행할 수 있게 해줌. (실질적으로 실행하면 됨.)
- inference_executable_file.py : 추론을 위해 실행하는 파일.
- requirements.txt

## llama2 file
- train_executable_file.py : 훈련 실행 파일
- inference_executable_file.py : 추론 실행 파일
- original_model_inference_executable_file.py : 파인튜닝 훈련을 진행하지 않은 원래 모델 추론 실행 파일
- requirements.txt

2024-05-17 04:45 UTC, Kim-Yul commented
## stable diffusion file
`dataset .py` : 사용자의 이미지 파일을 torch에서 사용할 수 있게 변환하고, 로드하는 작업을 진행
`generate.py` : 이미지를 생성 (사용자가 훈련시킬 이미지 class의 정규화 이미지를 생성하거나 모델의 추론을 통해 이미지를 생성할 때 필요함.)
`train.py` : 모델 훈련을 진행함.
`train_executable_file.py` : main 실행 파일에 넣어야 하는 args 값을 변수로 선언하여 실행할 수 있게 해줌. (실질적으로 실행하면 됨.)
`inference_executable_file.py` : 추론을 위해 실행하는 파일.
`requirements.txt`

### 상황별 필요 파일
train : 총 3개, `train.py`, `train_executable_file.py`, `dataset.py`
inference : 총 2개, `inference_executable_file.py`, `generate.py`

## llama2 file
`train_executable_file.py` : 훈련 실행 파일
`inference_executable_file.py` : 추론 실행 파일
`original_model_inference_executable_file.py` : 파인튜닝 훈련을 진행하지 않은 원래 모델 추론 실행 파일
`requirements.txt`

### 상황별 필요 파일
train : `train_excutable_file.py`
inference : `inference_excutable_file.py`

2024-05-17 04:45 UTC, Kim-Yul commented
작업완료했습니다. 확인바랍니다.

2024-05-17 06:04 UTC, jhM00n commented on foundation_model/llama2_7b_chat_hf/original_model_inference_executable_file.py
> +    'I want to express the word love emotionally, but please recommend 2 sophisticated love expression sentences.\n',
이게 prompt인거죠?

2024-05-17 16:01 UTC, QueueMin requested changes

2024-05-17 17:02 UTC, jhM00n commented
diffusion 인퍼런스 코드의 경우 최종 확정된 코드인가요? ray 관련 애기를 하셨던거 같아서

2024-05-18 09:30 UTC, Kim-Yul commented
수정 반영하였습니다. diffusion에서 inference에 ray 이용이 불가능할 경우를 대비하여 뺄 수 있는지.. 찾아보도록 하겠습니다.
llama2 데이터셋은 사용자 지정을 가져와 훈련할 수 있도록 변경했습니다.
데이터 형식은 parquet이어야 하며, 파케이(parquet)이란 하둡에서 칼럼방식으로 저장하는 저장 포맷을 말합니다.
훈련하고자 하는 포맷에 따라 다를 것 같은데 llama2의 Q and A 포맷은 지정되어 있다는 점만 참고해주시면 될 것 같습니다.

2024-05-18 13:15 UTC, mh3ong requested changes

2024-05-18 13:15 UTC, mh3ong commented on foundation_model/stable_diffusion/inference_executable_file.py
> +            return {"filename": filenames}
이 __call__ function에서는 여러 prompt를 받아서 for loop을 도는 것으로 보임.
이 코드를 하나의 prompt에 대해서만 처리하는 것으로 수정할 필요가 있음.
또한, image file을 바로 저장하는 것이 아니라 base64 형태로 return할 필요가 있음.

2024-05-18 13:15 UTC, mh3ong commented on foundation_model/stable_diffusion/inference_executable_file.py
> +        ).take_all()
사용자는 요청을 보낼때 한개씩 만 요청을 보내기에 ray data를 통한 분산 batch inference 처리 불필요.

2024-05-18 13:15 UTC, mh3ong commented on foundation_model/stable_diffusion/inference_executable_file.py
> +    )
base64 image를 가져와서 print 같은걸로 처리해놓고, 나중에 @jhM00n 가 사용할 수 있도록 변경.

2024-05-18 13:15 UTC, mh3ong commented on foundation_model/stable_diffusion/inference_executable_file.py
> +    run(args)
args를 통해 하지말고, os environment variable을 통해 받아올 수 있도록 해야 작업이 원활하게 진행될 것 같음. 또한 os env는 염두만하고, 수정이 필요한것은 일반적인 변수값으로서 static하게 설정되는게 필요함.

2024-05-18 15:02 UTC, mh3ong requested changes

2024-05-18 15:02 UTC, mh3ong commented on foundation_model/stable_diffusion/inference_executable_file.py
> +        return {"filename": filenames}
base64 처리는 언제할 예정?

2024-05-18 15:40 UTC, mh3ong commented
llama gpu에서 쓰는거맞나요? 추론속도가 상당히 느린거같은데

2024-05-19 02:17 UTC, Kim-Yul commented
llama2 gpu 사용 여부에 대해서는 다시 확인해보겠습니다.

2024-05-19 08:36 UTC, Kim-Yul commented
<img width="652" alt="image" src="https://github.com/kookmin-sw/capstone-2024-12/assets/65997015/76c2483b-974f-46fc-92fe-afa9eee0317e">

추론 작업 중 cuda로 이동하여 진행하는 것을 확인했습니다..

2024-05-19 08:38 UTC, mh3ong commented
ok, 일단 지금 문제가되는거는 python에서 memory 처리 관련 문제라 별도 내용인듯.

2024-05-19 08:44 UTC, Kim-Yul commented
확인했습니다.

@jhM00n llama2 requirements.txt 분리 하였습니다. 확인 부탁드립니다.

2024-05-19 08:45 UTC, mh3ong commented
diffusion model load할떄, model_path는 어떻게 설정해야되는거죠?
```OSError: Error no file named model_index.json found in directory /app/model/stable_diffusion.```

2024-05-19 08:46 UTC, Kim-Yul reviewed
작업진행 완료

2024-05-19 08:48 UTC, Kim-Yul commented
> diffusion model load할떄, model_path는 어떻게 설정해야되는거죠?
OSError: Error no file named model_index.json found in directory /app/model/stable_diffusion.

diffusion 모델의 압축을 푼 디렉토리의 경로를 설정해주셔야 합니다.

2024-05-19 08:53 UTC, jhM00n commented
diffusion 모델의 압축을 풀 경우 경로가  `/app/model/stable_diffusion/models--CompVis--stable-diffusion-v1-4/blobs | snapshots / ...`인데, 제가 설정한 경로는 `app/model/stable_diffusion`이거든요. 뒤에 models--...도 같이 붙여줘야 할까요?

2024-05-19 08:53 UTC, mh3ong commented
그러면 모델 불러오는 경로가 대체 어떤 내용물이 있어야된다는것인지?

2024-05-19 08:56 UTC, Kim-Yul commented
> diffusion 모델의 압축을 풀 경우 경로가 /app/model/stable_diffusion/models--CompVis--stable-diffusion-v1-4/blobs | snapshots / ...인데, 제가 설정한 경로는 app/model/stable_diffusion이거든요. 뒤에 models--...도 같이 붙여줘야 할까요?

네 model--CompVis--stable-diffusion-v1-4/snapshots/b~ 로 지정해주셔야 합니다.
제가 blobs 폴더가 없어도 되는지 체크해봤는데, 없을 때 에러가 발생해서 함께 올렸습니다.
그래서 경로가 좀 길더라도 다 지정해주셔야 합니다.

2024-05-19 08:57 UTC, Kim-Yul commented
> 그러면 모델 불러오는 경로가 대체 어떤 내용물이 있어야된다는것인지?

아래와 같이 지정한 경로 아래에 폴더 7개 및 기타 파일이 존재해야 합니다.
![image](https://github.com/kookmin-sw/capstone-2024-12/assets/65997015/60707a22-530a-43d6-9856-0508a51f743d)

2024-05-19 08:59 UTC, jhM00n commented
models-.../snapshots/b95..9ce 까지 지정하란거죠?

2024-05-19 09:00 UTC, Kim-Yul commented
> ../models-.../snapshots/b95..9ce 까지 지정하란거죠?


네 맞습니다.

2024-05-19 09:17 UTC, mh3ong commented
그렇다면 훈련 종료 후 최종 종료시에는 해당 폴더만 압축되게할 수 없는지?

2024-05-19 09:24 UTC, Kim-Yul commented
> 그렇다면 훈련 종료 후 최종 종료시에는 해당 폴더만 압축되게할 수 없는지?

가능합니다. 최종 훈련된 모델에서는 저렇게 긴 경로로 지정하지 않아도 잘 실행되더라고요.
파인튜닝 되지 않은 모델은 저렇게 지정 안하면 훈련이 안되더라고요. 혹시 모르니 다시 확인해보도록 하겠습니다.

2024-05-19 09:29 UTC, mh3ong commented
아하 그러면 어차피 저걸로 또 train할 수 있으니 snapshot 내의 폴더이름을 따는 technique가 필요하겠군요 일단 지금 상태를 유지하는걸로 합시다.

2024-05-19 10:44 UTC, mh3ong commented
추후 수정 필요시 추가 open

2024-05-19 10:44 UTC, merged