ray 를 위한 nodepool 추가 및 ResNet34 예시 코드 작성
kookmin-sw/capstone-2024-12 pull request #75
Opened 2024-05-14 07:03 UTC by seungwoo1124

제곧내

2024-05-14 07:37 UTC, mh3ong commented
trello 참고해서 예시코드에 반영하고,
예시코드에는 sskai_load_data.py와 requireents.txt도 포함되어야 함.

2024-05-14 07:53 UTC, seungwoo1124 commented
sskai_load_data.py 에서는 어떤 내용이 들어가야 하나요?
데이터 파일을 받아오고 그대로 입력에만 넣을 수 있는 형태로 반환하는 함수가 있으면 될까요?
데이터 파일의 이름은 상관이 없나요?

2024-05-14 07:53 UTC, mh3ong commented
x, y를 return하는데, 각각 torchtensor여야 합니다.

2024-05-14 07:53 UTC, mh3ong commented
데이터파일의 이름도 사용자가 지정하는것입니다.

2024-05-14 07:55 UTC, mh3ong commented
regression에서 사용한 sskai_load_data.py 예시
```python3
def sskai_load_data():
  import pandas as pd
  import torch
  data = pd.read_csv("./salary.csv")
  x = torch.tensor(data["YearsExperience"].values, dtype=torch.float32).reshape(-1, 1)
  y = torch.tensor(data["Salary"].values, dtype=torch.float32).reshape(-1, 1)

  return x, y
```

pandas는 requirements.txt에 정의되어 추가로 설치됩니다.

2024-05-14 09:31 UTC, seungwoo1124 commented
완료

2024-05-14 10:43 UTC, mh3ong requested changes

2024-05-14 10:43 UTC, mh3ong commented on example/ResNet34_CIFAR-10/sskai_load_data.py
> +    sskai_load_data()
x, y를 return하도록 해야함.

2024-05-14 10:43 UTC, mh3ong commented on example/ResNet34_CIFAR-10/requirements.txt
> +torch==2.0.1
requirements에 numpy, torch는 필요하지 않음. (이미 추가되어있음.)

2024-05-15 12:46 UTC, seungwoo1124 commented on example/ResNet34_CIFAR-10/sskai_load_data.py
> +    sskai_load_data()
완료

2024-05-15 12:46 UTC, seungwoo1124 commented on example/ResNet34_CIFAR-10/requirements.txt
> +torch==2.0.1
제거 완료.
파일 자체를 없애기보단 requirements.txt 를 빈 파일로 만들었음

2024-05-16 14:01 UTC, mh3ong commented
approved, merge

2024-05-16 14:01 UTC, mh3ong approved these changes

2024-05-16 14:01 UTC, merged