Lambda를 통한 Infra 생성/삭제 Lambda Function IaC 제작
kookmin-sw/capstone-2024-12 pull request #9
Opened 2024-03-26 03:53 UTC by jhM00n

variables.tf에서 prefix와 registry의 이름을 무엇으로 할지 고민이 필요함

variables.tf만 작성하면 작동하도록 해놓았음

2024-03-26 06:34 UTC, mh3ong requested changes
tf_test 삭제

2024-03-26 06:34 UTC, mh3ong commented on inference/lambda_IaC/lambda_terraform/lambda/main.tf
> +}
Serverless Inference Architecture를 만들기 위한 권한으로 수정
lambda, s3, apigateway, cloudwatch

2024-03-26 06:34 UTC, mh3ong commented on inference/lambda_IaC/lambda_terraform/main.tf
> +  profile = var.awscli_profile
Lambda에서 만드는데 profile이 왜 필요 ?

2024-03-26 06:34 UTC, mh3ong commented on inference/lambda_IaC/lambda_terraform/variables.tf.sample
> +}
민감정보는 Sample에서 삭제

2024-03-26 06:34 UTC, mh3ong commented on inference/lambda_IaC/user_infrastructure_deploy/terraform_deploy/lambda.py
> +    local_dir = '/tmp/tf-test'
bucket / folder 정보를 사용자/model?project? 별로 분할하는 logic 추가 필요

2024-03-26 06:34 UTC, mh3ong commented on inference/lambda_IaC/user_infrastructure_deploy/terraform_deploy/tf_test/backend.tf
> +    }
민감정보 삭제

2024-03-26 06:34 UTC, mh3ong commented on inference/lambda_IaC/user_infrastructure_deploy/terraform_deploy/tf_test/backend.tf
> +    }
이 부분을 parameter로서 api gateway로부터 받아야할 필요가 있음. (variable 처리)

2024-03-26 06:39 UTC, mh3ong requested changes

2024-03-26 06:39 UTC, mh3ong commented on inference/lambda_IaC/user_infrastructure_deploy/terraform_deploy/lambda.py
> +        'body': 'Terraform Applied and Destroyed Successfully'
apply일 경우, endpoint url을 뱉어야할 필요가 있음.
destroy일 경우, 삭제 성공 message를 뱉어야 함.

2024-03-26 06:39 UTC, mh3ong commented on inference/lambda_IaC/user_infrastructure_deploy/terraform_deploy/lambda.py
> +    subprocess.run([terraform_binary, "destroy", "-auto-approve"])
api reqeust의 따라서 apply냐 destroy냐 처리 필요.

2024-03-27 05:57 UTC, jhM00n commented on inference/lambda_IaC/user_infrastructure_deploy/terraform_deploy/tf_test/backend.tf
> +    }
이 부분은 merge 후 처리

2024-03-27 05:57 UTC, merged